"use client";

import { useState, useRef, useEffect } from "react";
import { Heart, Share2, Download, Printer, Copy, Link2, Mail, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { useAuth } from "@/hooks/useAuth";
import { useSavedRecipes } from "@/hooks/useSavedRecipes";
import { generateRecipePDF, recipeToText } from "@/lib/pdf-generator";
import type { Recipe } from "@/types";

interface RecipeActionsProps {
  recipe: Recipe;
  onRemove?: () => void;
  showRemove?: boolean;
  className?: string;
}

export function RecipeActions({ recipe, onRemove, showRemove, className }: RecipeActionsProps) {
  const { user } = useAuth();
  const { saveRecipe, unsaveRecipe, isRecipeSaved } = useSavedRecipes();
  const [shareMenuOpen, setShareMenuOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [shareMessage, setShareMessage] = useState<string | null>(null);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const shareRef = useRef<HTMLDivElement>(null);
  const saved = isRecipeSaved(recipe.id);

  // Close share menu on click outside
  useEffect(() => {
    if (!shareMenuOpen) return;
    const handleClick = (e: MouseEvent) => {
      if (shareRef.current && !shareRef.current.contains(e.target as Node)) setShareMenuOpen(false);
    };
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, [shareMenuOpen]);

  const handleSave = async () => {
    if (!user) { window.location.href = "/auth/login"; return; }
    setSaving(true);
    if (saved) await unsaveRecipe(recipe.id);
    else await saveRecipe(recipe);
    setSaving(false);
  };

  const getOrCreateShareUrl = async (): Promise<string | null> => {
    if (shareUrl) return shareUrl;
    try {
      const res = await fetch("/api/recipes/share", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ recipe }),
      });
      const data = await res.json();
      if (data.shareUrl) { setShareUrl(data.shareUrl); return data.shareUrl; }
    } catch { /* ignore */ }
    return null;
  };

  const showToast = (msg: string) => {
    setShareMessage(msg);
    setTimeout(() => setShareMessage(null), 2500);
  };

  const handleCopyLink = async () => {
    const url = await getOrCreateShareUrl();
    if (url) { await navigator.clipboard.writeText(url); showToast("Link copied!"); }
    else showToast("Failed to create link");
    setShareMenuOpen(false);
  };

  const handleCopyText = async () => {
    await navigator.clipboard.writeText(recipeToText(recipe));
    showToast("Copied to clipboard!");
    setShareMenuOpen(false);
  };

  const handlePDF = () => {
    generateRecipePDF(recipe);
    setShareMenuOpen(false);
  };

  const handleEmail = async () => {
    const url = await getOrCreateShareUrl();
    const subject = encodeURIComponent(`Check out this Freshwell recipe: ${recipe.title}`);
    const body = encodeURIComponent(`Check out this Freshwell recipe!\n\n${recipe.title}\n${recipe.description}\n\n${url || ""}\n\nGenerated by Freshwell - Low Carb Recipes`);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
    setShareMenuOpen(false);
  };

  const handleWhatsApp = async () => {
    const url = await getOrCreateShareUrl();
    const text = encodeURIComponent(`Check out this Freshwell recipe: ${recipe.title}\n${url || ""}`);
    window.open(`https://wa.me/?text=${text}`, "_blank");
    setShareMenuOpen(false);
  };

  const handleTwitter = async () => {
    const url = await getOrCreateShareUrl();
    const text = encodeURIComponent(`Check out this Freshwell recipe: ${recipe.title}`);
    window.open(`https://twitter.com/intent/tweet?text=${text}&url=${encodeURIComponent(url || "")}`, "_blank");
    setShareMenuOpen(false);
  };

  const handleFacebook = async () => {
    const url = await getOrCreateShareUrl();
    window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url || "")}`, "_blank");
    setShareMenuOpen(false);
  };

  const handlePrint = () => {
    const text = recipeToText(recipe);
    const w = window.open("", "_blank");
    if (w) { w.document.write(`<pre style="font-family:system-ui;max-width:600px;margin:40px auto;line-height:1.6">${text}</pre>`); w.document.close(); w.print(); }
    setShareMenuOpen(false);
  };

  return (
    <div className={cn("flex items-center gap-1 relative", className)}>
      {/* Save */}
      <button
        onClick={(e) => { e.stopPropagation(); handleSave(); }}
        disabled={saving}
        className={cn("rounded-lg p-2 transition-colors cursor-pointer", saved ? "text-red-500 hover:bg-red-50" : "text-gray-400 hover:text-red-500 hover:bg-gray-100")}
        title={saved ? "Unsave" : "Save recipe"}
      >
        <Heart className={cn("h-4 w-4", saved && "fill-current")} />
      </button>

      {/* Share - uses fixed positioning to avoid z-index issues */}
      <div ref={shareRef} className="relative">
        <button
          onClick={(e) => { e.stopPropagation(); setShareMenuOpen(!shareMenuOpen); }}
          className="rounded-lg p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 transition-colors cursor-pointer"
          title="Share"
        >
          <Share2 className="h-4 w-4" />
        </button>

        {shareMenuOpen && (
          <div
            className="fixed inset-0 z-[9999]"
            onClick={(e) => { e.stopPropagation(); setShareMenuOpen(false); }}
          >
            <div
              className="absolute w-52 rounded-xl border border-gray-200 bg-white shadow-2xl py-1"
              style={{
                top: shareRef.current ? shareRef.current.getBoundingClientRect().top - 8 : 0,
                left: shareRef.current ? shareRef.current.getBoundingClientRect().left - 180 : 0,
                transform: "translateY(-100%)",
              }}
              onClick={(e) => e.stopPropagation()}
            >
              <p className="px-3 py-1.5 text-[10px] font-semibold text-gray-400 uppercase tracking-wider">Share</p>
              <button onClick={handleCopyLink} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer"><Link2 className="h-3.5 w-3.5" /> Copy Link</button>
              <button onClick={handleWhatsApp} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer"><span className="text-xs">💬</span> WhatsApp</button>
              <button onClick={handleFacebook} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer"><span className="text-xs">📘</span> Facebook</button>
              <button onClick={handleTwitter} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer"><span className="text-xs">🐦</span> X / Twitter</button>
              <button onClick={handleEmail} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer"><Mail className="h-3.5 w-3.5" /> Email</button>
              <div className="border-t border-gray-100 my-1" />
              <p className="px-3 py-1.5 text-[10px] font-semibold text-gray-400 uppercase tracking-wider">Export</p>
              <button onClick={handleCopyText} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer"><Copy className="h-3.5 w-3.5" /> Copy as Text</button>
              <button onClick={handlePDF} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer"><Download className="h-3.5 w-3.5" /> Download PDF</button>
              <button onClick={handlePrint} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer"><Printer className="h-3.5 w-3.5" /> Print</button>
            </div>
          </div>
        )}
      </div>

      {/* Remove */}
      {showRemove && onRemove && (
        <button onClick={(e) => { e.stopPropagation(); onRemove(); }} className="rounded-lg p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 transition-colors cursor-pointer" title="Remove">
          <X className="h-4 w-4" />
        </button>
      )}

      {/* Toast */}
      {shareMessage && (
        <div className="fixed top-4 left-1/2 -translate-x-1/2 z-[10000] whitespace-nowrap rounded-lg bg-gray-900 px-4 py-2 text-sm text-white shadow-lg">
          {shareMessage}
        </div>
      )}
    </div>
  );
}
