"use client";

import { useState, useRef, useEffect } from "react";
import { createPortal } from "react-dom";
import { Heart, Share2, Download, Printer, Copy, Link2, Mail, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { useAuth } from "@/hooks/useAuth";
import { useSavedRecipes } from "@/hooks/useSavedRecipes";
import { generateRecipePDF, recipeToText } from "@/lib/pdf-generator";
import type { Recipe } from "@/types";

interface RecipeActionsProps {
  recipe: Recipe;
  onRemove?: () => void;
  showRemove?: boolean;
  className?: string;
}

export function RecipeActions({ recipe, onRemove, showRemove, className }: RecipeActionsProps) {
  const { user } = useAuth();
  const { saveRecipe, unsaveRecipe, isRecipeSaved } = useSavedRecipes();
  const [shareMenuOpen, setShareMenuOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [shareMessage, setShareMessage] = useState<string | null>(null);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [menuPosition, setMenuPosition] = useState<{ top: number; left: number } | null>(null);
  const [mounted, setMounted] = useState(false);
  const shareButtonRef = useRef<HTMLButtonElement>(null);
  const saved = isRecipeSaved(recipe.id);

  useEffect(() => { setMounted(true); }, []);

  // Pre-fetch share URL when menu opens so social links work without async (popup-blocker safe)
  useEffect(() => {
    if (shareMenuOpen && !shareUrl) {
      fetch("/api/recipes/share", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ recipe }),
      })
        .then((r) => r.json())
        .then((data) => { if (data.shareUrl) setShareUrl(data.shareUrl); })
        .catch(() => { /* ignore */ });
    }
  }, [shareMenuOpen, shareUrl, recipe]);

  // Calculate menu position when opening
  useEffect(() => {
    if (shareMenuOpen && shareButtonRef.current) {
      const rect = shareButtonRef.current.getBoundingClientRect();
      const menuWidth = 224; // 14rem
      const menuHeight = 420;
      let left = rect.right - menuWidth;
      let top = rect.top - menuHeight - 8;

      // Keep menu on screen
      if (left < 8) left = 8;
      if (top < 8) top = rect.bottom + 8; // Flip below if no room above
      if (left + menuWidth > window.innerWidth - 8) left = window.innerWidth - menuWidth - 8;

      setMenuPosition({ top, left });
    }
  }, [shareMenuOpen]);

  const handleSave = async () => {
    if (!user) { window.location.href = "/auth/login"; return; }
    setSaving(true);
    if (saved) await unsaveRecipe(recipe.id);
    else await saveRecipe(recipe);
    setSaving(false);
  };

  const showToast = (msg: string) => { setShareMessage(msg); setTimeout(() => setShareMessage(null), 2500); };

  const handleCopyLink = async () => {
    if (shareUrl) {
      await navigator.clipboard.writeText(shareUrl);
      showToast("Link copied!");
    } else {
      showToast("Generating link...");
    }
    setShareMenuOpen(false);
  };

  const handleCopyText = async () => {
    await navigator.clipboard.writeText(recipeToText(recipe));
    showToast("Copied to clipboard!");
    setShareMenuOpen(false);
  };

  const handlePDF = () => { generateRecipePDF(recipe); setShareMenuOpen(false); };

  // Social share handlers - synchronous calls to window.open to avoid popup blockers
  const handleWhatsApp = () => {
    const url = shareUrl || "";
    const text = encodeURIComponent(`Check out this Freshwell recipe: ${recipe.title}${url ? "\n" + url : ""}`);
    window.open(`https://wa.me/?text=${text}`, "_blank", "noopener,noreferrer");
    setShareMenuOpen(false);
  };

  const handleTwitter = () => {
    const url = shareUrl || "";
    const text = encodeURIComponent(`Check out this Freshwell recipe: ${recipe.title}`);
    window.open(`https://twitter.com/intent/tweet?text=${text}${url ? "&url=" + encodeURIComponent(url) : ""}`, "_blank", "noopener,noreferrer");
    setShareMenuOpen(false);
  };

  const handleFacebook = () => {
    const url = shareUrl || window.location.href;
    window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`, "_blank", "noopener,noreferrer");
    setShareMenuOpen(false);
  };

  const handleEmail = () => {
    const url = shareUrl || "";
    const subject = encodeURIComponent(`Check out this Freshwell recipe: ${recipe.title}`);
    const body = encodeURIComponent(`Check out this Freshwell recipe!\n\n${recipe.title}\n${recipe.description}\n\n${url}\n\nGenerated by Freshwell`);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
    setShareMenuOpen(false);
  };

  const handlePrint = () => {
    const text = recipeToText(recipe);
    const w = window.open("", "_blank");
    if (w) { w.document.write(`<pre style="font-family:system-ui;max-width:600px;margin:40px auto;line-height:1.6">${text}</pre>`); w.document.close(); w.print(); }
    setShareMenuOpen(false);
  };

  // Share menu rendered via portal to escape modal overflow clipping
  const shareMenu = mounted && shareMenuOpen && menuPosition && createPortal(
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 z-[9998]"
        onClick={(e) => { e.stopPropagation(); setShareMenuOpen(false); }}
      />
      {/* Menu */}
      <div
        className="fixed w-56 rounded-xl border border-gray-200 bg-white shadow-2xl py-1 z-[9999]"
        style={{ top: menuPosition.top, left: menuPosition.left }}
        onClick={(e) => e.stopPropagation()}
      >
        <p className="px-3 py-1.5 text-[10px] font-semibold text-gray-400 uppercase tracking-wider">Share</p>
        <button onClick={handleCopyLink} className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer">
          <Link2 className="h-4 w-4 text-gray-400" /> Copy Link
        </button>
        <button onClick={handleWhatsApp} className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer">
          <svg className="h-4 w-4" viewBox="0 0 24 24" fill="#25D366"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg>
          WhatsApp
        </button>
        <button onClick={handleFacebook} className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer">
          <svg className="h-4 w-4" viewBox="0 0 24 24" fill="#1877F2"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>
          Facebook
        </button>
        <button onClick={handleTwitter} className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer">
          <svg className="h-4 w-4" viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
          X / Twitter
        </button>
        <button onClick={handleEmail} className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer">
          <Mail className="h-4 w-4 text-gray-400" /> Email
        </button>
        <div className="border-t border-gray-100 my-1" />
        <p className="px-3 py-1.5 text-[10px] font-semibold text-gray-400 uppercase tracking-wider">Export</p>
        <button onClick={handleCopyText} className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer">
          <Copy className="h-4 w-4 text-gray-400" /> Copy as Text
        </button>
        <button onClick={handlePDF} className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer">
          <Download className="h-4 w-4 text-gray-400" /> Download PDF
        </button>
        <button onClick={handlePrint} className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 cursor-pointer">
          <Printer className="h-4 w-4 text-gray-400" /> Print
        </button>
      </div>
    </>,
    document.body
  );

  const toast = mounted && shareMessage && createPortal(
    <div className="fixed top-4 left-1/2 -translate-x-1/2 z-[10000] whitespace-nowrap rounded-lg bg-gray-900 px-4 py-2 text-sm text-white shadow-lg">
      {shareMessage}
    </div>,
    document.body
  );

  return (
    <div className={cn("flex items-center gap-1", className)}>
      <button
        onClick={(e) => { e.stopPropagation(); handleSave(); }}
        disabled={saving}
        className={cn("rounded-lg p-2 transition-colors cursor-pointer", saved ? "text-red-500 hover:bg-red-50" : "text-gray-400 hover:text-red-500 hover:bg-gray-100")}
        title={saved ? "Unsave" : "Save recipe"}
      >
        <Heart className={cn("h-4 w-4", saved && "fill-current")} />
      </button>

      <button
        ref={shareButtonRef}
        onClick={(e) => { e.stopPropagation(); setShareMenuOpen(!shareMenuOpen); }}
        className="rounded-lg p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 transition-colors cursor-pointer"
        title="Share"
      >
        <Share2 className="h-4 w-4" />
      </button>

      {showRemove && onRemove && (
        <button onClick={(e) => { e.stopPropagation(); onRemove(); }} className="rounded-lg p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 transition-colors cursor-pointer" title="Remove">
          <X className="h-4 w-4" />
        </button>
      )}

      {shareMenu}
      {toast}
    </div>
  );
}
