"use client";

import { jsPDF } from "jspdf";
import type { Recipe } from "@/types";
import { TRAFFIC_LIGHT_LABELS } from "@/types";

export function generateRecipePDF(recipe: Recipe): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let y = 20;

  // Helper: add new page if needed
  const checkPage = (needed: number = 20) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(recipe.title, margin, y);
  y += 10;

  // Traffic light + meta
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  const meta = `${TRAFFIC_LIGHT_LABELS[recipe.overallTrafficLight]} | Prep: ${recipe.prepTime} mins | Cook: ${recipe.cookTime} mins | Serves: ${recipe.servings}`;
  doc.text(meta, margin, y);
  y += 8;

  // Description
  if (recipe.description) {
    doc.setTextColor(80);
    doc.setFontSize(11);
    const descLines = doc.splitTextToSize(recipe.description, contentWidth);
    doc.text(descLines, margin, y);
    y += descLines.length * 5 + 5;
  }

  // Line
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Ingredients
  doc.setTextColor(0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Ingredients", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  for (const ing of recipe.ingredients) {
    checkPage();
    const text = `\u2022  ${ing.quantity}${ing.unit ? " " + ing.unit : ""} ${ing.name}`;
    doc.text(text, margin + 2, y);
    y += 6;
  }

  y += 6;
  checkPage(30);

  // Line
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Method
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Method", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  recipe.instructions.forEach((step, i) => {
    checkPage(15);
    const lines = doc.splitTextToSize(`${i + 1}. ${step}`, contentWidth - 5);
    doc.text(lines, margin + 2, y);
    y += lines.length * 5 + 4;
  });

  // Footer
  y += 10;
  checkPage();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Freshwell - Based on the Freshwell Low Carb Programme", margin, y);

  // Save
  const filename = recipe.title.toLowerCase().replace(/[^a-z0-9]+/g, "-") + ".pdf";
  doc.save(filename);
}

export function recipeToText(recipe: Recipe): string {
  const lines = [
    recipe.title,
    "=".repeat(recipe.title.length),
    "",
    recipe.description,
    "",
    `Traffic Light: ${TRAFFIC_LIGHT_LABELS[recipe.overallTrafficLight]}`,
    `Prep: ${recipe.prepTime} mins | Cook: ${recipe.cookTime} mins | Serves: ${recipe.servings}`,
    "",
    "INGREDIENTS",
    "-----------",
    ...recipe.ingredients.map(
      (i) => `- ${i.quantity}${i.unit ? " " + i.unit : ""} ${i.name}`
    ),
    "",
    "METHOD",
    "------",
    ...recipe.instructions.map((s, i) => `${i + 1}. ${s}`),
    "",
    "---",
    "Generated by Freshwell",
  ];
  return lines.join("\n");
}
